#!/bin/sh

# Bring the various environment-sensitive definitions out of J jobs and to here:
#NCO refers to these as 'job card' variables
if [ -z $PE_LIBSCI_GENCOMPS_INTEL_x86_64 ] ; then
#acorn
source /apps/prod/lmodules/startLmod
module load envvar/1.0
module load PrgEnv-intel
module load intel/19.1.3.304
module load intel/19.1.3.304/cray-mpich/8.1.4
module load prod_util/2.0.3
module load w3nco/2.4.1
module load w3emc/2.7.3
module load wgrib2/2.0.8
module load bacio bufr g2
module load libpng/1.6.37
module load zlib/1.2.11
module load jasper/2.0.16
module load netcdf/4.7.4
module load imagemagick
#wcoss:
#  module load ips/19.0.5.281 impi/19.0.5
#  module load prod_envir/1.1.0
#  module load prod_util/1.1.5
#  module load grib_util/1.1.1
#  module load bufr_dumplist/2.3.0
#  module load dumpjb/5.1.0
#  module load NetCDF/4.5.0
#  module load lsf/10.1
#  module list
fi

#set -xe
set -x

export HOMEbase=/u/Robert.Grumbine/rgdev
export seaice_analysis_ver=v4.4.0
export HOMEseaice_analysis=$HOMEbase/seaice_analysis.${seaice_analysis_ver}

export MODULEPATH_ROOT=/usrx/local/prod/modulefiles

export COMINsst_base=${COMINsst_base:-`compath.py gfs/prod/sst`}

#Important that these be after compaty.py
export RUN_ENVIR=not_nco
export envir=developer

export NET=omb
export RUN=sice
export cyc=${cyc:-00}
export cycle=t${cyc}z
export pid=$$
export jobid=$pid


if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ] ; then
  #NCO
  export HOMEbase=/nw${envir}
  export COMROOT=/com
  export COMINsst_base=/com/gfs/prod
  export PCOMROOT=/pcom/${envir}/mrf
else
  #developer
  export COMROOT=/u/Robert.Grumbine/noscrub/com/
  #export DATAROOT=/gpfs/dell2/ptmp/wx21rg/
  export DATAROOT=~/scratch/
  export HOMEbase=/u/Robert.Grumbine/rgdev
  export jlogfile=/u/Robert.Grumbine/jlogfile
  export PCOMROOT=/u/Robert.Grumbine/noscrub/pcom/$RUN
  export SENDCOM=YES

  #export COMROOT=/u/Robert.Grumbine/noscrub/com/${NET}/${envir}
fi

########################################################
#DBN stuff
########################################################
#export DBNROOT=/nwprod/spa_util/fakedbn
export DBNROOT=/iodprod/dbnet_siphon
if [ "$envir" = "prod" ] ; then
  export SENDDBN=YES
  export SENDDBN_NTC=YES
else
  if [ $envir = "para" ] ; then
    export SENDDBN=YES
    export SENDDBN_NTC=NO
    export DBN_ALERT_TYPE=TBD_PARA
  else
    export SENDDBN=NO
    export SENDDBN_NTC=NO
  fi
fi
########################################################
